### ISSUE TITLE
Tensorboard not working

### ISSUE THREAD

**Issue by stefanDeveloper** [stefanDeveloper/explainable-prediction_covid19#10]
Tensorboard data existiert nicht

**Comment by DavidHector** [comment]
Der Pfad ist glaube falsch, mit 

%tensorboard --logdir results/logs/training 

gehts bei mir.

**Comment by DavidHector** [comment]
![Screenshot from 2021-08-19 14-44-10](https://user-images.githubusercontent.com/70699798/130070630-347aeaf7-1b72-4bab-b137-4613b1938b68.png)

**Comment by stefanDeveloper** [comment]
> Der Pfad ist glaube falsch, mit
> 
> %tensorboard --logdir results/logs/training
> 
> gehts bei mir.

Weird, das ging bei mir nicht

**Comment by DavidHector** [comment]
Ist das Training bei dir durchgelaufen?

**Comment by DavidHector** [comment]
covid-cxr/results/logs/training sollte eine Datei sein, die events.out.tfevents.1629376750.david-desktop-linux.6548.248209.v2 heißt. Natürlich mit deinem Rechnernamen.

**Comment by stefanDeveloper** [comment]
Ja ist es, ich schaue noch mal nach. Aber wenn es bei dir so geht, habe ich wohl etwas falsch eingestellt

**Comment by DavidHector** [comment]
Also ich hab jetzt mal einen branch local-version gemacht, da geht bei mir jetzt alles, inklusive LIME und tensorboard (https://github.com/stefanDeveloper/explainable-prediction_covid19/blob/local-version/covid-cxr/documents/generated_images/db96a050.jpg_exp_20210819-160210.png)

**Comment by DavidHector** [comment]
In der train.py war aber noch einiges falsch, die get_class_weights Funktion gibt einfach kein dictionary aus, wenns einen class_multiplier gibt und zumindest bei mir gabs zwei entries in metrics, die fälschlicherweise den gleichen Namen hatten
