### ISSUE TITLE
Fix data `preprocess.py`

### ISSUE THREAD

**Issue by stefanDeveloper** [stefanDeveloper/explainable-prediction_covid19#6]
- [x] Try to fix [preprocess.py](https://github.com/aildnont/covid-cxr/blob/master/src/data/preprocess.py) and check if COVID images can be processed

**Comment by DavidHector** [comment]
Beim MILA Dataset (covid-chestxray-dataset) wurde das Label in der metadata.csv geändert, aber nicht in preprocess.py, deswegen wurden keine COVID images da gefunden, obwohl es eigentlich ~500 gibt. RSNA enthält gar keine COVID labels und Figure1 ist winzig.

**Comment by DavidHector** [comment]
Sollte jetzt aber gefixed sein
